In [2]:
import gzip
import csv
import json
import pandas as pd

In [ ]:
#reading 100o rows from data
data = pd.read_csv('flightlist.csv.gz', nrows=1000, compression='gzip',
                   error_bad_lines=False)
print(data)

In [3]:
#column list
list(data)

['callsign',
 'number',
 'icao24',
 'registration',
 'typecode',
 'origin',
 'destination',
 'firstseen',
 'lastseen',
 'day']

In [8]:
#to drop if any value in the row has a nan
df_clean = data.dropna(how='any')
df_clean

,callsign,number,icao24,registration,typecode,origin,destination,firstseen,lastseen,day
13,CES516,MU516,7807d6,B-6538,A332,RJBB,RJBB,2019-12-31 06:02:26+00:00,2020-01-01 03:08:39+00:00,2020-01-01 00:00:00+00:00
17,VOI938,Y4938,0d036e,XA-VOI,A319,KLAX,KPDX,2019-12-31 06:43:17+00:00,2020-01-01 04:24:08+00:00,2020-01-01 00:00:00+00:00
19,CSN328,CZ328,780737,B-6137,A388,KLAX,YSSY,2019-12-31 06:47:17+00:00,2020-01-01 22:14:43+00:00,2020-01-01 00:00:00+00:00
20,UAE358,EK358,8963db,A6-EPL,B77W,OMDB,OMDB,2019-12-31 06:48:26+00:00,2020-01-01 01:41:45+00:00,2020-01-01 00:00:00+00:00
24,UAL9,UA9,a2a2e3,N26906,B788,KSFO,KSFO,2019-12-31 08:05:55+00:00,2020-01-01 14:46:17+00:00,2020-01-01 00:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...
976,UAL2271,UA2271,a4dad4,N41140,B752,KLAS,KEWR,2019-12-31 20:58:41+00:00,2020-01-01 01:01:22+00:00,2020-01-01 00:00:00+00:00
977,AAL612,AA612,a968f8,N705UW,A319,TBPB,KCLT,2019-12-31 20:58:48+00:00,2020-01-01 01:28:28+00:00,2020-01-01 00:00:00+00:00
980,UAE194,EK194,896316,A6-ENT,B77W,LPAR,OMDB,2019-12-31 20:59:34+00:00,2020-01-01 03:53:58+00:00,2020-01-01 00:00:00+00:00
981,DAL460,DL460,a9acb8,N722TW,B752,KJFK,UT13,2019-12-31 20:59:45+00:00,2020-01-01 01:20:38+00:00,2020-01-01 00:00:00+00:00
982,JAL17,JL17,8621ea,JA620J,B763,CYVR,CYVR,2019-12-31 20:59:53+00:00,2020-01-01 18:11:46+00:00,2020-01-01 00:00:00+00:00