In [1]:
import gzip
import csv
import json
import pandas as pd
import datetime

In [2]:
#reading 100o rows from data
data = pd.read_csv('flightlist.csv.gz', compression='gzip',
                   error_bad_lines=False)
data

,callsign,number,icao24,registration,typecode,origin,destination,firstseen,lastseen,day
0,SVA816,NaN,710064,HZ-AK24,B77W,NaN,NaN,2019-12-31 00:19:47+00:00,2020-01-01 13:27:28+00:00,2020-01-01 00:00:00+00:00
1,THY183,NaN,4ba9c1,TC-JNA,A332,NaN,LTBW,2019-12-31 00:25:26+00:00,2020-01-01 07:48:41+00:00,2020-01-01 00:00:00+00:00
2,CES738,MU738,781418,NaN,NaN,YMML,YSSY,2019-12-31 01:08:54+00:00,2020-01-01 01:45:29+00:00,2020-01-01 00:00:00+00:00
3,CES771,MU771,781858,NaN,NaN,YSSY,EHAM,2019-12-31 01:29:25+00:00,2020-01-01 04:08:28+00:00,2020-01-01 00:00:00+00:00
4,HAL5,HA5,a455ea,N379HA,A332,KLAS,NaN,2019-12-31 02:23:05+00:00,2020-01-01 08:52:18+00:00,2020-01-01 00:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...
1519098,AIC549,NaN,800441,VT-PPH,A321,VOMM,NaN,2020-01-31 23:44:05+00:00,2020-01-31 23:58:58+00:00,2020-01-31 00:00:00+00:00
1519099,NSE8685,9R8685,0ac332,FAC-1193,AT46,NaN,SKBO,2020-01-31 23:44:11+00:00,2020-01-31 23:57:20+00:00,2020-01-31 00:00:00+00:00
1519100,ENY4166,NaN,abb639,N854AE,NaN,KCLT,NaN,2020-01-31 23:44:16+00:00,2020-01-31 23:54:48+00:00,2020-01-31 00:00:00+00:00
1519101,UTY3207,QQ3207,7c1acf,VH-FKX,F50,NaN,YPAD,2020-01-31 23:46:09+00:00,2020-01-31 23:57:35+00:00,2020-01-31 00:00:00+00:00
1519102,ASA9465,NaN,a24dc1,N248AK,B739,KTPA,52FA,2020-01-31 23:46:24+00:00,2020-01-31 23:59:17+00:00,2020-01-31 00:00:00+00:00

In [3]:
#column list
list(data)

['callsign',
 'number',
 'icao24',
 'registration',
 'typecode',
 'origin',
 'destination',
 'firstseen',
 'lastseen',
 'day']

In [4]:
#to drop if any value in the row has a nan
df_clean = data.dropna(how='any')
df_clean

,callsign,number,icao24,registration,typecode,origin,destination,firstseen,lastseen,day
13,CES516,MU516,7807d6,B-6538,A332,RJBB,RJBB,2019-12-31 06:02:26+00:00,2020-01-01 03:08:39+00:00,2020-01-01 00:00:00+00:00
17,VOI938,Y4938,0d036e,XA-VOI,A319,KLAX,KPDX,2019-12-31 06:43:17+00:00,2020-01-01 04:24:08+00:00,2020-01-01 00:00:00+00:00
19,CSN328,CZ328,780737,B-6137,A388,KLAX,YSSY,2019-12-31 06:47:17+00:00,2020-01-01 22:14:43+00:00,2020-01-01 00:00:00+00:00
20,UAE358,EK358,8963db,A6-EPL,B77W,OMDB,OMDB,2019-12-31 06:48:26+00:00,2020-01-01 01:41:45+00:00,2020-01-01 00:00:00+00:00
24,UAL9,UA9,a2a2e3,N26906,B788,KSFO,KSFO,2019-12-31 08:05:55+00:00,2020-01-01 14:46:17+00:00,2020-01-01 00:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...
1518972,UAL1481,UA1481,aac954,N79402,B739,KIAH,KSAT,2020-01-31 23:17:36+00:00,2020-01-31 23:57:56+00:00,2020-01-31 00:00:00+00:00
1518984,ANA15,NH15,86787c,JA713A,B772,RJTK,RJOO,2020-01-31 23:19:21+00:00,2020-01-31 23:59:54+00:00,2020-01-31 00:00:00+00:00
1519045,PDT4731,PT4731,a94c2a,N699AE,E145,KPHL,KMDT,2020-01-31 23:28:13+00:00,2020-01-31 23:58:29+00:00,2020-01-31 00:00:00+00:00
1519076,UAE322,EK322,8960ed,A6-EDL,A388,OMDB,OMDB,2020-01-31 23:35:30+00:00,2020-01-31 23:47:19+00:00,2020-01-31 00:00:00+00:00
1519085,UAE376,EK376,896479,A6-EUO,A388,OMDB,OMDB,2020-01-31 23:37:28+00:00,2020-01-31 23:48:16+00:00,2020-01-31 00:00:00+00:00

In [5]:
df_clean['firstseen'] = df_clean['firstseen'].str.strip('+00:00')

C:\Users\Owner\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [6]:
df_clean

,callsign,number,icao24,registration,typecode,origin,destination,firstseen,lastseen,day
13,CES516,MU516,7807d6,B-6538,A332,RJBB,RJBB,2019-12-31 06:02:26,2020-01-01 03:08:39+00:00,2020-01-01 00:00:00+00:00
17,VOI938,Y4938,0d036e,XA-VOI,A319,KLAX,KPDX,2019-12-31 06:43:17,2020-01-01 04:24:08+00:00,2020-01-01 00:00:00+00:00
19,CSN328,CZ328,780737,B-6137,A388,KLAX,YSSY,2019-12-31 06:47:17,2020-01-01 22:14:43+00:00,2020-01-01 00:00:00+00:00
20,UAE358,EK358,8963db,A6-EPL,B77W,OMDB,OMDB,2019-12-31 06:48:26,2020-01-01 01:41:45+00:00,2020-01-01 00:00:00+00:00
24,UAL9,UA9,a2a2e3,N26906,B788,KSFO,KSFO,2019-12-31 08:05:55,2020-01-01 14:46:17+00:00,2020-01-01 00:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...
976,UAL2271,UA2271,a4dad4,N41140,B752,KLAS,KEWR,2019-12-31 20:58:41,2020-01-01 01:01:22+00:00,2020-01-01 00:00:00+00:00
977,AAL612,AA612,a968f8,N705UW,A319,TBPB,KCLT,2019-12-31 20:58:48,2020-01-01 01:28:28+00:00,2020-01-01 00:00:00+00:00
980,UAE194,EK194,896316,A6-ENT,B77W,LPAR,OMDB,2019-12-31 20:59:34,2020-01-01 03:53:58+00:00,2020-01-01 00:00:00+00:00
981,DAL460,DL460,a9acb8,N722TW,B752,KJFK,UT13,2019-12-31 20:59:45,2020-01-01 01:20:38+00:00,2020-01-01 00:00:00+00:00
982,JAL17,JL17,8621ea,JA620J,B763,CYVR,CYVR,2019-12-31 20:59:53,2020-01-01 18:11:46+00:00,2020-01-01 00:00:00+00:00

In [6]:
df_clean['lastseen'] = df_clean['lastseen'].str.strip('+00:00')

C:\Users\Owner\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [7]:
df_clean

,callsign,number,icao24,registration,typecode,origin,destination,firstseen,lastseen,day
13,CES516,MU516,7807d6,B-6538,A332,RJBB,RJBB,2019-12-31 06:02:26,2020-01-01 03:08:39,2020-01-01 00:00:00+00:00
17,VOI938,Y4938,0d036e,XA-VOI,A319,KLAX,KPDX,2019-12-31 06:43:17,2020-01-01 04:24:08,2020-01-01 00:00:00+00:00
19,CSN328,CZ328,780737,B-6137,A388,KLAX,YSSY,2019-12-31 06:47:17,2020-01-01 22:14:43,2020-01-01 00:00:00+00:00
20,UAE358,EK358,8963db,A6-EPL,B77W,OMDB,OMDB,2019-12-31 06:48:26,2020-01-01 01:41:45,2020-01-01 00:00:00+00:00
24,UAL9,UA9,a2a2e3,N26906,B788,KSFO,KSFO,2019-12-31 08:05:55,2020-01-01 14:46:17,2020-01-01 00:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...
1518972,UAL1481,UA1481,aac954,N79402,B739,KIAH,KSAT,2020-01-31 23:17:36,2020-01-31 23:57:56,2020-01-31 00:00:00+00:00
1518984,ANA15,NH15,86787c,JA713A,B772,RJTK,RJOO,2020-01-31 23:19:21,2020-01-31 23:59:54,2020-01-31 00:00:00+00:00
1519045,PDT4731,PT4731,a94c2a,N699AE,E145,KPHL,KMDT,2020-01-31 23:28:13,2020-01-31 23:58:29,2020-01-31 00:00:00+00:00
1519076,UAE322,EK322,8960ed,A6-EDL,A388,OMDB,OMDB,2020-01-31 23:35:3,2020-01-31 23:47:19,2020-01-31 00:00:00+00:00
1519085,UAE376,EK376,896479,A6-EUO,A388,OMDB,OMDB,2020-01-31 23:37:28,2020-01-31 23:48:16,2020-01-31 00:00:00+00:00

In [8]:
df_clean['day'] = df_clean['day'].str.strip('+00:00')

C:\Users\Owner\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [9]:
df_clean

,callsign,number,icao24,registration,typecode,origin,destination,firstseen,lastseen,day
13,CES516,MU516,7807d6,B-6538,A332,RJBB,RJBB,2019-12-31 06:02:26,2020-01-01 03:08:39,2020-01-01
17,VOI938,Y4938,0d036e,XA-VOI,A319,KLAX,KPDX,2019-12-31 06:43:17,2020-01-01 04:24:08,2020-01-01
19,CSN328,CZ328,780737,B-6137,A388,KLAX,YSSY,2019-12-31 06:47:17,2020-01-01 22:14:43,2020-01-01
20,UAE358,EK358,8963db,A6-EPL,B77W,OMDB,OMDB,2019-12-31 06:48:26,2020-01-01 01:41:45,2020-01-01
24,UAL9,UA9,a2a2e3,N26906,B788,KSFO,KSFO,2019-12-31 08:05:55,2020-01-01 14:46:17,2020-01-01
...,...,...,...,...,...,...,...,...,...,...
1518972,UAL1481,UA1481,aac954,N79402,B739,KIAH,KSAT,2020-01-31 23:17:36,2020-01-31 23:57:56,2020-01-31
1518984,ANA15,NH15,86787c,JA713A,B772,RJTK,RJOO,2020-01-31 23:19:21,2020-01-31 23:59:54,2020-01-31
1519045,PDT4731,PT4731,a94c2a,N699AE,E145,KPHL,KMDT,2020-01-31 23:28:13,2020-01-31 23:58:29,2020-01-31
1519076,UAE322,EK322,8960ed,A6-EDL,A388,OMDB,OMDB,2020-01-31 23:35:3,2020-01-31 23:47:19,2020-01-31
1519085,UAE376,EK376,896479,A6-EUO,A388,OMDB,OMDB,2020-01-31 23:37:28,2020-01-31 23:48:16,2020-01-31